package tools

import (
	"crypto/hmac"
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"io"
	"mime"
	"net/http"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"
)

const (
	DefaultUploadTTL     = 5 * time.Minute
	DefaultUploadMaxSize = 100 * 1024 * 1024
	uploadTempPrefix     = "webex-upload-"
)

// UploadManager manages short-lived HTTP uploads for MCP clients that cannot
// expose their local filesystem to the HTTP-mode MCP server.
type UploadManager struct {
	baseURL string
	dir     string
	secret  []byte
	ttl     time.Duration
	maxSize int64
	now     func() time.Time

	mu      sync.Mutex
	uploads map[string]*PendingUpload
	stop    chan struct{}
}

// PendingUpload tracks one signed upload reservation.
type PendingUpload struct {
	ID          string    `json:"uploadId"`
	FileName    string    `json:"fileName"`
	ContentType string    `json:"contentType,omitempty"`
	Path        string    `json:"-"`
	ExpiresAt   time.Time `json:"expiresAt"`
	MaxSize     int64     `json:"maxSizeBytes"`
	Size        int64     `json:"sizeBytes,omitempty"`
	Uploaded    bool      `json:"uploaded"`
}

// UploadReservation is returned to MCP clients by webex_uploads_request_url.
type UploadReservation struct {
	UploadID     string `json:"uploadId"`
	UploadURL    string `json:"uploadUrl"`
	FileName     string `json:"fileName"`
	ExpiresAt    string `json:"expiresAt"`
	ExpiresIn    int64  `json:"expiresIn"`
	MaxSizeBytes int64  `json:"maxSizeBytes"`
	CurlCommand  string `json:"curlCommand"`
}

// NewUploadManager creates an upload manager rooted at baseURL.
func NewUploadManager(baseURL, dir string, maxSize int64) (*UploadManager, error) {
	if dir == "" {
		dir = filepath.Join(os.TempDir(), "webex-go-mcp-uploads")
	}
	if maxSize <= 0 {
		maxSize = DefaultUploadMaxSize
	}
	if err := os.MkdirAll(dir, 0700); err != nil {
		return nil, fmt.Errorf("failed to create upload directory: %w", err)
	}
	if err := sweepUploadDirectory(dir); err != nil {
		return nil, fmt.Errorf("failed to sweep stale uploads: %w", err)
	}

	secret := make([]byte, 32)
	if _, err := rand.Read(secret); err != nil {
		return nil, fmt.Errorf("failed to generate upload signing secret: %w", err)
	}

	m := &UploadManager{
		baseURL: strings.TrimRight(baseURL, "/"),
		dir:     dir,
		secret:  secret,
		ttl:     DefaultUploadTTL,
		maxSize: maxSize,
		now:     time.Now,
		uploads: make(map[string]*PendingUpload),
		stop:    make(chan struct{}),
	}
	go m.cleanupLoop()
	return m, nil
}

// Close stops background cleanup and removes temporary upload files.
func (m *UploadManager) Close() error {
	close(m.stop)
	m.mu.Lock()
	defer m.mu.Unlock()
	for id, upload := range m.uploads {
		if upload.Path != "" {
			_ = os.Remove(upload.Path)
		}
		delete(m.uploads, id)
	}
	return nil
}

// RequestUpload creates a short-lived signed URL for uploading a file.
func (m *UploadManager) RequestUpload(fileName, contentType string) (*UploadReservation, error) {
	id, err := randomHex(16)
	if err != nil {
		return nil, err
	}

	fileName = sanitizeUploadFileName(fileName)
	expiresAt := m.now().Add(m.ttl)
	expiresUnix := expiresAt.Unix()
	sig := m.sign(id, expiresUnix)
	uploadURL := fmt.Sprintf("%s/uploads/%s?expires=%d&sig=%s", m.baseURL, id, expiresUnix, sig)

	m.mu.Lock()
	m.uploads[id] = &PendingUpload{
		ID:          id,
		FileName:    fileName,
		ContentType: contentType,
		ExpiresAt:   expiresAt,
		MaxSize:     m.maxSize,
	}
	m.mu.Unlock()

	return &UploadReservation{
		UploadID:     id,
		UploadURL:    uploadURL,
		FileName:     fileName,
		ExpiresAt:    expiresAt.UTC().Format(time.RFC3339),
		ExpiresIn:    int64(m.ttl.Seconds()),
		MaxSizeBytes: m.maxSize,
		CurlCommand:  fmt.Sprintf("curl -X PUT -T %s %s", shellQuoteArg("/path/to/"+fileName), shellQuoteArg(uploadURL)),
	}, nil
}

// ConsumeUpload returns an uploaded file and removes its reservation. The caller
// is responsible for deleting upload.Path after use.
func (m *UploadManager) ConsumeUpload(id string) (*PendingUpload, error) {
	m.mu.Lock()
	defer m.mu.Unlock()

	upload, ok := m.uploads[id]
	if !ok {
		return nil, fmt.Errorf("uploadId %q was not found or has expired", id)
	}
	if m.now().After(upload.ExpiresAt) {
		delete(m.uploads, id)
		if upload.Path != "" {
			_ = os.Remove(upload.Path)
		}
		return nil, fmt.Errorf("uploadId %q has expired", id)
	}
	if !upload.Uploaded || upload.Path == "" {
		return nil, fmt.Errorf("uploadId %q has not been uploaded yet", id)
	}

	delete(m.uploads, id)
	return upload, nil
}

// ServeHTTP accepts PUT uploads for URLs generated by RequestUpload.
func (m *UploadManager) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPut {
		writeUploadError(w, http.StatusMethodNotAllowed, "method_not_allowed", "Use PUT to upload file bytes")
		return
	}

	id := strings.TrimPrefix(r.URL.Path, "/uploads/")
	if id == "" || strings.Contains(id, "/") {
		writeUploadError(w, http.StatusBadRequest, "invalid_upload_id", "Invalid upload id")
		return
	}

	expiresUnix, err := strconv.ParseInt(r.URL.Query().Get("expires"), 10, 64)
	if err != nil {
		writeUploadError(w, http.StatusBadRequest, "invalid_signature", "Missing or invalid expires parameter")
		return
	}
	if m.now().Unix() > expiresUnix {
		writeUploadError(w, http.StatusUnauthorized, "upload_expired", "Upload URL has expired")
		return
	}
	if !m.validSignature(id, expiresUnix, r.URL.Query().Get("sig")) {
		writeUploadError(w, http.StatusUnauthorized, "invalid_signature", "Invalid upload signature")
		return
	}

	m.mu.Lock()
	upload, ok := m.uploads[id]
	m.mu.Unlock()
	if !ok {
		writeUploadError(w, http.StatusNotFound, "upload_not_found", "Upload reservation was not found")
		return
	}
	if r.ContentLength > upload.MaxSize {
		writeUploadError(w, http.StatusRequestEntityTooLarge, "file_too_large", "File exceeds maximum upload size")
		return
	}

	tmp, err := os.CreateTemp(m.dir, uploadTempPrefix+id+"-*")
	if err != nil {
		writeUploadError(w, http.StatusInternalServerError, "server_error", "Failed to create upload file")
		return
	}
	path := tmp.Name()
	written, copyErr := io.Copy(tmp, io.LimitReader(r.Body, upload.MaxSize+1))
	closeErr := tmp.Close()
	if copyErr != nil || closeErr != nil {
		_ = os.Remove(path)
		writeUploadError(w, http.StatusInternalServerError, "server_error", "Failed to store upload")
		return
	}
	if written > upload.MaxSize {
		_ = os.Remove(path)
		writeUploadError(w, http.StatusRequestEntityTooLarge, "file_too_large", "File exceeds maximum upload size")
		return
	}

	contentType := r.Header.Get("Content-Type")
	if contentType == "" {
		contentType = upload.ContentType
	}
	if contentType == "" {
		contentType = mime.TypeByExtension(filepath.Ext(upload.FileName))
	}
	if contentType == "" {
		contentType = "application/octet-stream"
	}

	m.mu.Lock()
	if oldPath := upload.Path; oldPath != "" {
		_ = os.Remove(oldPath)
	}
	upload.Path = path
	upload.Size = written
	upload.ContentType = contentType
	upload.Uploaded = true
	m.mu.Unlock()

	w.Header().Set("Content-Type", "application/json")
	_ = json.NewEncoder(w).Encode(map[string]interface{}{
		"uploadId":    upload.ID,
		"fileName":    upload.FileName,
		"sizeBytes":   written,
		"contentType": contentType,
		"expiresAt":   upload.ExpiresAt.UTC().Format(time.RFC3339),
	})
}

func (m *UploadManager) cleanupLoop() {
	ticker := time.NewTicker(time.Minute)
	defer ticker.Stop()
	for {
		select {
		case <-m.stop:
			return
		case <-ticker.C:
			m.cleanupExpired()
		}
	}
}

func (m *UploadManager) cleanupExpired() {
	now := m.now()
	m.mu.Lock()
	defer m.mu.Unlock()
	for id, upload := range m.uploads {
		if now.After(upload.ExpiresAt) {
			if upload.Path != "" {
				_ = os.Remove(upload.Path)
			}
			delete(m.uploads, id)
		}
	}
}

func sweepUploadDirectory(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, entry := range entries {
		if entry.IsDir() || !isUploadTempFileName(entry.Name()) {
			continue
		}
		if err := os.Remove(filepath.Join(dir, entry.Name())); err != nil && !os.IsNotExist(err) {
			return err
		}
	}
	return nil
}

func isUploadTempFileName(name string) bool {
	if strings.HasPrefix(name, uploadTempPrefix) {
		return true
	}
	// Legacy temp files used the raw 32-char hex upload id as the prefix.
	if len(name) < 34 || name[32] != '-' {
		return false
	}
	for _, r := range name[:32] {
		if (r < '0' || r > '9') && (r < 'a' || r > 'f') {
			return false
		}
	}
	return true
}

func (m *UploadManager) sign(id string, expiresUnix int64) string {
	mac := hmac.New(sha256.New, m.secret)
	_, _ = fmt.Fprintf(mac, "PUT\n%s\n%d", id, expiresUnix)
	return hex.EncodeToString(mac.Sum(nil))
}

func (m *UploadManager) validSignature(id string, expiresUnix int64, sig string) bool {
	expected := m.sign(id, expiresUnix)
	return hmac.Equal([]byte(expected), []byte(sig))
}

func randomHex(bytes int) (string, error) {
	buf := make([]byte, bytes)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("failed to generate random id: %w", err)
	}
	return hex.EncodeToString(buf), nil
}

func sanitizeUploadFileName(fileName string) string {
	fileName = strings.TrimSpace(strings.ReplaceAll(fileName, "\x00", ""))
	fileName = strings.ReplaceAll(fileName, "\\", "/")
	fileName = filepath.Base(fileName)
	if fileName == "" || fileName == "." || fileName == string(filepath.Separator) {
		return "attachment"
	}
	return fileName
}

func shellQuoteArg(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\"'\"'") + "'"
}

func writeUploadError(w http.ResponseWriter, status int, code, description string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(map[string]string{
		"error":             code,
		"error_description": description,
	})
}
